<?php
/**
 * @author Denis Khodakovskii <denis.khodakovskiy@gmail.com>
 */

declare(strict_types=1);

namespace This\ORM\Migrations\Handler;

use This\Contracts\RequestInterface;

final readonly class Migrator
{
    public function __construct(
        private string $migrationsPath,
        private RequestInterface $request,
    ) {
    }

    public function __invoke(string $action): string
    {
        if (
            !file_exists($this->migrationsPath)
            || !is_dir($this->migrationsPath)
            || !is_writable($this->migrationsPath)
        ) {
            throw new \RuntimeException('Migrations directory is not writable');
        }

        return match ($action) {
            'create' => $this->create(),
            default => throw new \RuntimeException('Unknown migration action: ' . $action),
        };
    }

    private function create(): string
    {
        $name = $this->request->getAttribute('name', $this->request->getAttribute(0));
        $name = $this->request->getAttribute('name', $this->request->getAttribute(0));
        $time = (new \DateTimeImmutable())->format('YmdHis');

        $code = <<<CODE
<?php
/**
 * @author THIS CLI
 */

declare(strict_types=1);

use This\ORM\Migrations\Migration;

class Version{$time}_{$name} extends Migration
{
    public function up(): void
    {
        //implement up method
    }
    
    public function down(): void
    {
        //implement down method
    }
    
    public function draft(): bool
    {
        return true;
    }
    
    public function draftReason(): ?string
    {
        return 'Autogenerated migration. Review required.';
    }
}

CODE;

        file_put_contents("{$this->migrationsPath}/Version{$time}_{$name}.php", $code);

        return sprintf('%s has been generated', "{$this->migrationsPath}/Version{$time}_{$name}.php") . PHP_EOL;
    }
}
